services:
  web:
    build: .
    container_name: fastapi-container-yml
    ports:
      - "8000:8000"
    volumes:
      - ./test.db:/app/test.db
    depends_on:
      - prometheus
      - redis
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboard_provisioning.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-data: