services:
  web:
    build: .
    container_name: fastapi-container-yml
    ports:
      - "8000:8000"
    volumes:
      - ./test.db:/app/test.db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_STREAM=logs
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-container-yml
    ports:
      - "6379:6379"
    restart: unless-stopped
  