services:
  web:
    build: .
    container_name: fastapi-container-yml
    ports:
      - "8000:8000"
    volumes:
      - ./test.db:/app/test.db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_STREAM=logs
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - SECRET_KEY=asecretkey
    depends_on:
      - prometheus
      - redis
    networks:
      - monitoring

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - monitoring

  consumer:
    build:
      context: .
      dockerfile: /services/Dockerfile.consumer
    container_name: consumer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_STREAM=logs
    networks:
      - monitoring
    volumes:
      - ./services/redis_messages.log:/app/redis_messages.log
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
        - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning/dashboards
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_SERVER_DOMAIN: localhost
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SECURITY_COOKIE_SAME_SITE: none
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:

  prometheus-data:
    driver: local